### PR TITLE
Fixed table 5 nov news

### PR DESCRIPTION
**Pull request by armv64**
Changed the values in the pitstop1.csv file and rebuild the whole thing

### CODE REVIEW

**Comment by armv64** [comment]
@witusj

**Comment by armv64** [comment]
Hi @witusj 

the fix in commit c58e6eb didn't really work out. Yes, we have a Benno in our class now, but the table is still broken.
Please consider accepting this PR request.

**Comment by witusj** [comment]
Could you please identify yourself?

**Comment by armv64** [comment]
@witusj 

I really value my privacy and really, I'm trying to help you with this website.

You can checkout my changes to see I don't push anything weird whatsoever.

**Comment by witusj** [comment]
Thanks for the effort. I changed the csv-file. It was an issue translating Excel to csv. Almost always a mess. Used another tool and now it works.

**Comment by armv64** [comment]
Could have used my PR to fix it but c3937ea seems to fix it aswell. 
Thanks for fixing it @witusj 

Closing this PR

**Pull request closed without merging**
